### ISSUE TITLE
show memory

### ISSUE THREAD

**Issue by claesmk** [NCATComp410/comp410_fall_2020#15]

**Comment by claesmk** [comment]
show memory is very short - so show memory and show memory detail should be parsed together as one section

**Comment by claesmk** [comment]
show memory and show memory detail (https://github.com/NCATComp410/comp410_fall_2020/issues/16) should be done together by a single person since show memory is a very short section without much to do.

**Comment by scotter567** [comment]
I was wondering if anybody knew if when using the get_show_section function when I pass 'memory' as the argument is it supposed to also show the memory detail and memory region sections?

**Comment by claesmk** [comment]
The way the code is currently written - if the argument is 'memory' it would show both sections.  

```
def match_section(line, section):
    """Returns true if line matches section"""
    if line.startswith('----') and '---- ' + section in line:
        return True
    return False
```

Do you think this behavior should be changed to be more consistent?  If so, what improvement would you suggest making?

**Comment by scotter567** [comment]
I think the behavior as it stands is incorrect. If it were to only show the memory and memory detail sections I could see the argument because memory details is a direct extension of memory. But with it also showing the memory region section I believe this is incorrect. The I believe the conditional to check if we are at the beginning of a section should either be more literal, where we check for a line that starts with 18 dashes, then what ever section you are looking for then another, then another 18 dashes. 

After looking at the functionality of the match_section function I see it is used to start appending lines and stop appending lines. We could possibly add the section name as an argument to build a little more robustness in the condition.

**Comment by claesmk** [comment]
That's a great idea, but there is an issue - the first section has only 8 dashes, all the others have 18

```
-------- show tech-support detail --------
...
------------------ show tech-support license ------------------
```

How about a match something like this:
```
def match_section(line, section):
    """Returns true if line matches section"""
    if re.search(r'^[-]{8,18} ' + section + r' [-]{8,18}$', line):
        return True
    return False
```

As for the other problem with match_section, we could create a new function called is_section which would match any potentially valid section heading. 

I created https://github.com/NCATComp410/comp410_fall_2020/issues/26

Will work up some ideas and ask you to review it. Let me know what you think.

**Comment by claesmk** [comment]
Created a pull request https://github.com/NCATComp410/comp410_fall_2020/pull/27

**Comment by claesmk** [comment]
For sprint1 please create a new issue called "Create stub function for show memory" (and also one for the show memory detail) See the [storyboard](https://github.com/orgs/NCATComp410/projects/2?card_filter_query=milestone%3ASprint1) for examples

**Comment by scotter567** [comment]
#108
